---
settings:
  name: NetApp NFS Plug-in for VMware VAAI
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
    langs: us-en,ja-jp,zh-cn
sidebar:

  entries:
  - title: Home
    url: "/index.html"
  - title: Release Notes
    url: "/releasenotes.html"
  - title: Installing the NetApp NFS Plug-in 2.0 for VMware VAAI
    url: "/task_installing_the_netapp_nfs_plugin_for_vmware_vaai.html"
    entries:
  - title: Configuring export policies for ONTAP to allow VAAI over NFS
    url: "/task_configuring_export_policies_for_clustered_data_ontap_to_allow_vaai_over_nfs.html"
  - title: Legal Notices
    url: "/reference_legal_notices.html"
