---
settings:
  name: NetApp NFS Plug-in for VMware VAAI
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
    langs: us-en,ja-jp,zh-cn
sidebar:

  entries:
  - title: NetApp NFS Plug-in for VMware VAAI docs
    url: "/index.html"
  - title: Release Notes
    url: "/releasenotes.html"
  - title: Install NetApp NFS Plug-in for VMware VAAI
    url: "/task-install-netapp-nfs-plugin-for-vmware-vaai.html"
  - title: Configure export policies for ONTAP to allow VAAI over NFS
    url: "/task-configure-export-policies-for-clustered-data-ontap-to-allow-vaai-over-nfs.html"
  - title: Legal Notices
    url: "/reference-legal-notices.html"
